# Generated by Django 4.2.7 on 2025-11-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PatientData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Masculin"), ("F", "Féminin")], max_length=1
                    ),
                ),
                ("glucose", models.FloatField(help_text="Glucose (mmol/L)")),
                ("cholesterol", models.FloatField(help_text="Cholesterol (mmol/L)")),
                (
                    "triglycerides",
                    models.FloatField(help_text="Triglycerides (mmol/L)"),
                ),
                ("creatinine", models.FloatField(help_text="Creatinine (umol/L)")),
                ("uree", models.FloatField(help_text="Uree (mmol/L)")),
                ("uric_acid", models.FloatField(help_text="Uric Acid (umol/L)")),
                ("got", models.FloatField(help_text="GOT (U/L)")),
                ("gpt", models.FloatField(help_text="GPT (U/L)")),
                ("bilirubin", models.FloatField(help_text="Bilirubin Total (umol/L)")),
                ("smoking", models.BooleanField(default=False)),
                ("obesity", models.BooleanField(default=False)),
                ("family_history", models.BooleanField(default=False)),
                (
                    "diagnosis",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SAIN", "Patient Sain"),
                            ("DIABETE", "Diabète"),
                            ("HYPERLIPIDEMIE", "Hyperlipidémie"),
                            ("RENAL", "Insuffisance Rénale"),
                            ("HEPATIQUE", "Insuffisance Hépatique"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("prediction_made", models.BooleanField(default=False)),
            ],
        ),
    ]
