# Generated by Django 4.2.7 on 2025-11-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PatientData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Masculin"), ("F", "Féminin")], max_length=1
                    ),
                ),
                ("fever", models.BooleanField(default=False)),
                ("cough", models.BooleanField(default=False)),
                ("chest_pain", models.BooleanField(default=False)),
                ("shortness_breath", models.BooleanField(default=False)),
                ("fatigue", models.BooleanField(default=False)),
                ("headache", models.BooleanField(default=False)),
                ("nausea", models.BooleanField(default=False)),
                ("blood_pressure", models.IntegerField()),
                ("cholesterol", models.IntegerField()),
                ("blood_sugar", models.IntegerField()),
                ("smoking", models.BooleanField(default=False)),
                ("obesity", models.BooleanField(default=False)),
                ("family_history", models.BooleanField(default=False)),
                (
                    "diagnosis",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SAIN", "Patient Sain"),
                            ("DIABETE", "Diabète"),
                            ("HYPER", "Hypertension"),
                            ("CARDIAC", "Problème Cardiaque"),
                            ("RESPIRATORY", "Problème Respiratoire"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("prediction_made", models.BooleanField(default=False)),
            ],
        ),
    ]
